version: "3"
services:
  db:
    container_name: postgres-jpa
    image: postgres
    environment:
      POSTGRES_DB: jpa-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    restart: always